---
name: main branch tests

on:
  push:
    branches:
      - main

permissions:
  actions: write
  pull-requests: write
  statuses: write

jobs:
  linters:
    uses: ./.github/workflows/linters.yml
  tests:
    uses: ./.github/workflows/tests.yml
